#!/bin/bash
set -eu

. git-issue-mvp
. new_filename.sh

cmd=$1
shift

case "$cmd" in
  init)    git_issue_init "$@" ;;
  clone)   git_issue_clone "$@" ;;
  edit)    git_issue_edit "$@" ;;
  new)     git_issue_new "$@" ;;
  status)  git_issue_status "$@" ;;
  commit)  git_issue_commit "$@" ;;
  comment) git_issue_comment "$@" ;;
  log)     git_issue_log "$@" ;;
  list)    git_issue_list "$@" ;;
  list-full) git_issue_list_full "$@" ;; 
  show)    git_issue_show "$@" ;;
  search)  git_issue_search "$@" ;;
  push)    git_issue_push "$@" ;;
  fetch)   git_issue_fetch "$@" ;;
  merge)   git_issue_merge "$@" ;;
  pull)    git_issue_fetch "$@"
           git_issue_merge --rebase --audit ;;
  remote) git_issue_track "$@" ;;
  track)  git_issue_track "$@" ;;

  *)
    echo "usage for local   : git issue <init|edit|status|commit|comment|log|list|list-full|show|search>"
    echo "      for remotes : git issue <clone|track|push|fetch|merge>"
    exit 1
    ;;
esac
